# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twig < Formula
  desc "TUI to manage git worktrees and tmux sessions"
  homepage "https://github.com/Alex-Painter/twig"
  version "0.1.0"
  license "MIT"

  depends_on "gh" => :optional
  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alex-Painter/twig/releases/download/v0.1.0/twig_0.1.0_darwin_amd64.tar.gz"
      sha256 "d1fa4dd45b563dae41002144f46040e6d1f54cdbf12a8bb8ae46c7813f9edbe6"

      define_method(:install) do
        bin.install "twig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alex-Painter/twig/releases/download/v0.1.0/twig_0.1.0_darwin_arm64.tar.gz"
      sha256 "421be013929ab6bec43a31385034e3c2899498e7e6296eb8bf08454920e946d0"

      define_method(:install) do
        bin.install "twig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alex-Painter/twig/releases/download/v0.1.0/twig_0.1.0_linux_amd64.tar.gz"
      sha256 "517385284897924de1c401457e7e499754fe36eac91c6f3dc860972068025cbe"
      define_method(:install) do
        bin.install "twig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alex-Painter/twig/releases/download/v0.1.0/twig_0.1.0_linux_arm64.tar.gz"
      sha256 "4fe817708f0f617000540769c80bd6f983e0ba67b774c16ffc9213bf574ff636"
      define_method(:install) do
        bin.install "twig"
      end
    end
  end

  test do
    system "#{bin}/twig", "--version"
  end
end
